### ISSUE TITLE
cant compile xorg-server

### ISSUE THREAD

**Issue by agevlakh** [flydiscohuebr/nvidia-304#1]
When I try compile xorg server, got error:

dh_auto_configure: error: cd debian/build/main && ../../../configure --build=i686-linux-gnu --prefix=/usr --includedir=\${prefix}/include --mandir=\${prefix}/share/man --infodir=\${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-option-checking --disable-silent-rules --libdir=\${prefix}/lib/i386-linux-gnu --libexecdir=\${prefix}/lib/i386-linux-gnu --disable-maintainer-mode --disable-dependency-tracking --libdir=\${prefix}/lib --libexecdir=\${libdir}/xorg --disable-silent-rules --disable-static --without-dtrace --disable-strict-compilation --disable-debug --enable-unit-tests --with-int10=x86emu --with-os-vendor=Debian "--with-builderstring=xorg-server 2:1.19.2-1+deb12u12 (https://www.debian.org/support)" --with-xkb-path=/usr/share/X11/xkb --with-xkb-output=/var/lib/xkb --with-shared-memory-dir=/dev/shm --enable-mitshm --enable-xres --disable-xcsecurity --disable-tslib --enable-dbe --disable-xf86bigfont --enable-dpms --enable-xshmfence --disable-config-hal --enable-config-udev --enable-xorg --disable-linux-acpi --disable-linux-apm --disable-xquartz --disable-xwin --disable-xfake --disable-xfbdev --disable-install-setuid --with-default-font-path=/usr/share/fonts/X11/misc,/usr/share/fonts/X11/cyrillic,/usr/share/fonts/X11/100dpi/:unscaled,/usr/share/fonts/X11/75dpi/:unscaled,/usr/share/fonts/X11/Type1,/usr/share/fonts/X11/100dpi,/usr/share/fonts/X11/75dpi,built-ins --enable-composite --enable-record --enable-xv --enable-xvmc --enable-dga --enable-screensaver --enable-xdmcp --enable-xdm-auth-1 --enable-glx --enable-dri --enable-dri2 --enable-glamor --enable-dri3 --enable-libdrm --enable-present --enable-xinerama --enable-xf86vidmode --enable-xace --enable-xselinux --enable-xfree86-utils --enable-xwayland --enable-systemd-logind --with-systemd-daemon --enable-suid-wrapper --enable-xvfb --enable-xnest --enable-kdrive --enable-xephyr --with-sha1=libgcrypt --enable-xcsecurity ASFLAGS= "CFLAGS=-g -O2 -ffile-prefix-map=/home/anton/nvidia-304/Debian/xorg-server=. -fstack-protector-strong -Wformat -Werror=format-security" "CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2 -DPRE_RELEASE=0 " "CXXFLAGS=-g -O2 -ffile-prefix-map=/home/anton/nvidia-304/Debian/xorg-server=. -fstack-protector-strong -Wformat -Werror=format-security" DFLAGS=-frelease "FCFLAGS=-g -O2 -ffile-prefix-map=/home/anton/nvidia-304/Debian/xorg-server=. -fstack-protector-strong" "FFLAGS=-g -O2 -ffile-prefix-map=/home/anton/nvidia-304/Debian/xorg-server=. -fstack-protector-strong" "GCJFLAGS=-g -O2 -ffile-prefix-map=/home/anton/nvidia-304/Debian/xorg-server=. -fstack-protector-strong" "LDFLAGS=-Wl,-z,relro -Wl,-Bsymbolic" "OBJCFLAGS=-g -O2 -ffile-prefix-map=/home/anton/nvidia-304/Debian/xorg-server=. -fstack-protector-strong -Wformat -Werror=format-security" "OBJCXXFLAGS=-g -O2 -ffile-prefix-map=/home/anton/nvidia-304/Debian/xorg-server=. -fstack-protector-strong -Wformat -Werror=format-security" LIBS= returned exit code 1
make[1]: *** [debian/rules:184: override_dh_auto_configure] Ошибка 255
make[1]: выход из каталога «/home/anton/nvidia-304/Debian/xorg-server»
make: *** [debian/rules:167: build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2

Compile on debian 12 i386

**Comment by agevlakh** [comment]
Please help resolve this issue

**Comment by flydiscohuebr** [comment]
Fixed with: https://github.com/flydiscohuebr/nvidia-304/commit/39db4511dfc87cbc90fd0f2ba4d30356540beb96
```
sudo apt install libx11-xcb-dev
```
Or run the apt build-dep command again
