### ISSUE TITLE
error when build nvidia kernel module

### ISSUE THREAD

**Issue by agevlakh** [flydiscohuebr/nvidia-304#2]
Hello!
After compile and install all apps and reboot I get error:
Error running install command 'modprobe -i nvidia-legacy-304xx ' for module nvidia: retcode 127
Failed to insert module 'nvidia': Invalid argument

After some digging I understand. The kernel module Nvidia not built.
I install Linux headers. And when module Nvidia start building, I have error, can't build. This is make.log last strings. Please, help.

/usr/src/linux-headers-6.1.0-25-common/scripts/check-local-export /var/lib/dkms/nvidia-legacy-304xx/304.137/build/os-usermap.o
  if nm /var/lib/dkms/nvidia-legacy-304xx/304.137/build/os-usermap.o 2>/dev/null | grep -q ksymtab; then  gcc-12 -E -D__GENKSYMS -Wp,-MMD,/var/lib/dkms/nvidia-legacy-304xx/304.137/build/.os-usermap.o.d -nostdinc -I/usr/src/linux-headers-6.1.0-25-common/arch/x86/include -I./arch/x86/include/generated -I/usr/src/linux-headers-6.1.0-25-common/include -I./include -I/usr/src/linux-headers-6.1.0-25-common/arch/x86/include/uapi -I./arch/x86/include/generated/uapi -I/usr/src/linux-headers-6.1.0-25-common/include/uapi -I./include/generated/uapi -include /usr/src/linux-headers-6.1.0-25-common/include/linux/compiler-version.h -include /usr/src/linux-headers-6.1.0-25-common/include/linux/kconfig.h -include /usr/src/linux-headers-6.1.0-25-common/include/linux/compiler_types.h -D__KERNEL__ -fmacro-prefix-map=/usr/src/linux-headers-6.1.0-25-common/= -Wall -Wundef -Werror=strict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -fshort-wchar -fno-PIE -Werror=implicit-function-declaration -Werror=implicit-int -Werror=return-type -Wno-format-security -std=gnu11 -mno-sse -mno-mmx -mno-sse2 -mno-3dnow -mno-avx -fcf-protection=none -m32 -msoft-float -mregparm=3 -freg-struct-return -fno-pic -mpreferred-stack-boundary=2 -march=i686 -mtune=generic -Wa,-mtune=generic32 -ffreestanding -mstack-protector-guard-reg=fs -mstack-protector-guard-symbol=stack_chk_guard -Wno-sign-compare -fno-asynchronous-unwind-tables -mindirect-branch=thunk-extern -mindirect-branch-register -mindirect-branch-cs-prefix -fno-jump-tables -fno-delete-null-pointer-checks -Wno-frame-address -Wno-format-truncation -Wno-format-overflow -Wno-address-of-packed-member -O2 -fno-allow-store-data-races -Wframe-larger-than=1024 -fstack-protector-strong -Wno-main -Wno-unused-but-set-variable -Wno-unused-const-variable -Wno-dangling-pointer -fno-omit-frame-pointer -fno-optimize-sibling-calls -ftrivial-auto-var-init=zero -fno-stack-clash-protection -pg -mrecord-mcount -mfentry -DCC_USING_FENTRY -Wvla -Wno-pointer-sign -Wcast-function-type -Wno-stringop-truncation -Wno-stringop-overflow -Wno-restrict -Wno-maybe-uninitialized -Wno-array-bounds -Wno-alloc-size-larger-than -Wimplicit-fallthrough=5 -fno-strict-overflow -fno-stack-check -fconserve-stack -Werror=date-time -Werror=incompatible-pointer-types -Werror=designated-init -Wno-packed-not-aligned -g -I/var/lib/dkms/nvidia-legacy-304xx/304.137/build -Wall -MD -Wsign-compare -Wno-cast-qual -Wno-error -D__KERNEL -DMODULE -DNVRM -DNV_VERSION_STRING=\"304.137\" -Wno-unused-function -Wuninitialized -UDEBUG -U_DEBUG -DNDEBUG  -DMODULE  -DKBUILD_BASENAME='"os_usermap"' -DKBUILD_MODNAME='"nvidia"' -D__KBUILD_MODNAME=kmod_nvidia /var/lib/dkms/nvidia-legacy-304xx/304.137/build/os-usermap.c | scripts/genksyms/genksyms   -r /dev/null >> /var/lib/dkms/nvidia-legacy-304xx/304.137/build/.os-usermap.o.cmd; fi
  cat /var/lib/dkms/nvidia-legacy-304xx/304.137/build/nv-kernel-i386.o_shipped > /var/lib/dkms/nvidia-legacy-304xx/304.137/build/nv-kernel-i386.o
  ld.bfd -m elf_i386 -z noexecstack --no-warn-rwx-segments   -r -o /var/lib/dkms/nvidia-legacy-304xx/304.137/build/nvidia.o @/var/lib/dkms/nvidia-legacy-304xx/304.137/build/nvidia.mod
  {   echo /var/lib/dkms/nvidia-legacy-304xx/304.137/build/nvidia.ko; :; } > /var/lib/dkms/nvidia-legacy-304xx/304.137/build/modules.order
sh /usr/src/linux-headers-6.1.0-25-common/scripts/modules-check.sh /var/lib/dkms/nvidia-legacy-304xx/304.137/build/modules.order
make -f /usr/src/linux-headers-6.1.0-25-common/scripts/Makefile.modpost
   sed 's/ko$/o/'  /var/lib/dkms/nvidia-legacy-304xx/304.137/build/modules.order | scripts/mod/modpost -m      -o /var/lib/dkms/nvidia-legacy-304xx/304.137/build/Module.symvers -e -i Module.symvers -T -
ERROR: modpost: "native_write_cr4" [/var/lib/dkms/nvidia-legacy-304xx/304.137/build/nvidia.ko] undefined!

make[3]: *** [/usr/src/linux-headers-6.1.0-25-common/scripts/Makefile.modpost:127: /var/lib/dkms/nvidia-legacy-304xx/304.137/build/Module.symvers] Ошибка 1
make[2]: *** [/usr/src/linux-headers-6.1.0-25-common/Makefile:1986: modpost] Ошибка 2
make[2]: выход из каталога «/usr/src/linux-headers-6.1.0-25-686-pae»
make[1]: *** [Makefile:250: __sub-make] Ошибка 2
make[1]: выход из каталога «/usr/src/linux-headers-6.1.0-25-common»
make: *** [Makefile:338: module] Ошибка 2

**Comment by flydiscohuebr** [comment]
> ERROR: modpost: "native_write_cr4" [/var/lib/dkms/nvidia-legacy-304xx/304.137/build/nvidia.ko] undefined!  
  
https://github.com/flydiscohuebr/nvidia-304?tab=readme-ov-file#i-cant-use-the-driver-on-debian-32-bits-the-installation-fails  
You need a kernel with the LKDTM module enabled, for this you can recompile with the **CONFIG_LKDTM** option enabled  

I have an older version of the kernel that I compiled with this module in the past, if you are interested the link is below  

https://www.dropbox.com/scl/fi/s1unu9n8sn34ff4leedri/kernel-6.1.67-i686-custom-lkdtm-nonpae.zip?rlkey=ozzngbbwsgt4vp8b382roouq5&dl=1

**Comment by agevlakh** [comment]
Hello! Thank you very much, everything works with your kernel, the video card is detected. Only the brightness is not adjustable, although if I switch to Intel, I have a physical switch for video cards in my laptop, then the brightness adjustment works there. Maybe you know how to adjust the brightness on the Nvidia driver?

**Comment by flydiscohuebr** [comment]
> Hello! Thank you very much, everything works with your kernel, the video card is detected. Only the brightness is not adjustable, although if I switch to Intel, I have a physical switch for video cards in my laptop, then the brightness adjustment works there. Maybe you know how to adjust the brightness on the Nvidia driver?  

Try adding ```Option "RegistryDwords" "EnableBrightnessControl=1"``` on **section device** in your xorg.conf

```
Section "Device"
    Identifier     "Device0"
    Driver         "nvidia"
    Option "RegistryDwords" "EnableBrightnessControl=1 #goes here
    VendorName     "NVIDIA Corporation"
EndSection
```

**Comment by agevlakh** [comment]
> > Hello! Thank you very much, everything works with your kernel, the video card is detected. Only the brightness is not adjustable, although if I switch to Intel, I have a physical switch for video cards in my laptop, then the brightness adjustment works there. Maybe you know how to adjust the brightness on the Nvidia driver?
> 
> Try adding `Option "RegistryDwords" "EnableBrightnessControl=1"` on **section device** in your xorg.conf
> 
> ```
> Section "Device"
>     Identifier     "Device0"
>     Driver         "nvidia"
>     Option "RegistryDwords" "EnableBrightnessControl=1 #goes here
>     VendorName     "NVIDIA Corporation"
> EndSection
> ```
> 
> Or use the kernel parameter `nvidia.NVreg_RegistryDwords=EnableBrightnessControl=1`

It works! Thank you
